spring:
  application:
    name: micro.uaa
  jpa:
    hibernate:
      ddl-auto: none
  datasource: 
    url:  jdbc:mysql://localhost:3306/jdbc_authentication
    username: root
    password: {Password}
    initialization-mode: never
    
server:
  port: 7777
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

security:
  oauth2:
    client:
      client-id: antonio
      client-secret: elsecreto


config:
  security:
    oauth:
      client:
        id: app
        secret: elsecreto
      jwt:
        key: 123
        
