#HTTP Server
server:
  port: 2222
 
#Spring Config
spring:
  application:
    name: producto.service
  jpa:
  
    properties:
      hibernate:
        jdbc: time_zone = TimeZone
    generate-ddl: true

#Discovery Server Access
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    appname: producto.service
      
#Security Config
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:7777/user
